// pink
// purple
// orange
// creamsicle
// cream
// reddish
// highlight

const PINK = '#CC99CC';
const PURPLE = '#9999FF';
const ORANGE = '#FF9900';
const PEACH = '#FF9966';
const BEIGE = '#FFCC99';
const REDDISH = '#CC6666';
const HIGHLIGHT = '#F8FBDB';
const RED = '#D61402';

const TEXT_YELLOW = '#FAE607';
const TEXT_YELLOW_MELLOW = '#D6C71C';

const PINK_REDALERT = '#D53540';
const PURPLE_REDALERT = '#E01E1E';
const ORANGE_REDALERT = '#EE0000';
const PEACH_REDALERT = '#E5402F';
const BEIGE_REDALERT = '#FF5A5A';
const REDDISH_REDALERT = '#CE3535';
const HIGHLIGHT_REDALERT = '#FFBBBB';

export { PINK, PURPLE, ORANGE, PEACH, BEIGE, REDDISH, HIGHLIGHT, RED,
	TEXT_YELLOW, TEXT_YELLOW_MELLOW,
	PINK_REDALERT, PURPLE_REDALERT, ORANGE_REDALERT, PEACH_REDALERT,
	BEIGE_REDALERT, REDDISH_REDALERT, HIGHLIGHT_REDALERT };